name: Daily Game Review Video

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '0 12 * * *'  # runs every day at 12:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to generate video
        env:
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: |
          python your_script.py  # <-- change to your actual script name

      - name: Check for output.mp4
        run: |
          if [ ! -f output.mp4 ]; then
            echo "output.mp4 not found!"
            exit 1
          fi

      - name: Upload artifact (optional - for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: generated-video
          path: output.mp4
